// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataserver_msg.proto

#ifndef PROTOBUF_dataserver_5fmsg_2eproto__INCLUDED
#define PROTOBUF_dataserver_5fmsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dataserver_msg {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_dataserver_5fmsg_2eproto();
void protobuf_AssignDesc_dataserver_5fmsg_2eproto();
void protobuf_ShutdownFile_dataserver_5fmsg_2eproto();

class ChargingFlag;
class Control_CMD;
class Control_CMD_Init_Config;
class GeneralData;
class Position;
class Response_CMD;
class Response_CMD_Response_flag;
class Velocity;

// ===================================================================

class Position : public ::google::protobuf::Message {
 public:
  Position();
  virtual ~Position();

  Position(const Position& from);

  inline Position& operator=(const Position& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Position& default_instance();

  void Swap(Position* other);

  // implements Message ----------------------------------------------

  inline Position* New() const { return New(NULL); }

  Position* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Position& from);
  void MergeFrom(const Position& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Position* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // required double y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // optional double theta = 3;
  bool has_theta() const;
  void clear_theta();
  static const int kThetaFieldNumber = 3;
  double theta() const;
  void set_theta(double value);

  // optional int32 seq = 4 [default = -1];
  bool has_seq() const;
  void clear_seq();
  static const int kSeqFieldNumber = 4;
  ::google::protobuf::int32 seq() const;
  void set_seq(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dataserver_msg.Position)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_theta();
  inline void clear_has_theta();
  inline void set_has_seq();
  inline void clear_has_seq();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  double theta_;
  ::google::protobuf::int32 seq_;
  friend void  protobuf_AddDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_AssignDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_dataserver_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static Position* default_instance_;
};
// -------------------------------------------------------------------

class Velocity : public ::google::protobuf::Message {
 public:
  Velocity();
  virtual ~Velocity();

  Velocity(const Velocity& from);

  inline Velocity& operator=(const Velocity& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Velocity& default_instance();

  void Swap(Velocity* other);

  // implements Message ----------------------------------------------

  inline Velocity* New() const { return New(NULL); }

  Velocity* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Velocity& from);
  void MergeFrom(const Velocity& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Velocity* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double v = 1 [default = 0];
  bool has_v() const;
  void clear_v();
  static const int kVFieldNumber = 1;
  double v() const;
  void set_v(double value);

  // required double w = 2 [default = 0];
  bool has_w() const;
  void clear_w();
  static const int kWFieldNumber = 2;
  double w() const;
  void set_w(double value);

  // optional double v2 = 3 [default = 0];
  bool has_v2() const;
  void clear_v2();
  static const int kV2FieldNumber = 3;
  double v2() const;
  void set_v2(double value);

  // @@protoc_insertion_point(class_scope:dataserver_msg.Velocity)
 private:
  inline void set_has_v();
  inline void clear_has_v();
  inline void set_has_w();
  inline void clear_has_w();
  inline void set_has_v2();
  inline void clear_has_v2();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double v_;
  double w_;
  double v2_;
  friend void  protobuf_AddDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_AssignDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_dataserver_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static Velocity* default_instance_;
};
// -------------------------------------------------------------------

class ChargingFlag : public ::google::protobuf::Message {
 public:
  ChargingFlag();
  virtual ~ChargingFlag();

  ChargingFlag(const ChargingFlag& from);

  inline ChargingFlag& operator=(const ChargingFlag& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChargingFlag& default_instance();

  void Swap(ChargingFlag* other);

  // implements Message ----------------------------------------------

  inline ChargingFlag* New() const { return New(NULL); }

  ChargingFlag* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChargingFlag& from);
  void MergeFrom(const ChargingFlag& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ChargingFlag* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 chargingFlag = 1 [default = 0];
  bool has_chargingflag() const;
  void clear_chargingflag();
  static const int kChargingFlagFieldNumber = 1;
  ::google::protobuf::int32 chargingflag() const;
  void set_chargingflag(::google::protobuf::int32 value);

  // optional int32 seq = 2 [default = 0];
  bool has_seq() const;
  void clear_seq();
  static const int kSeqFieldNumber = 2;
  ::google::protobuf::int32 seq() const;
  void set_seq(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dataserver_msg.ChargingFlag)
 private:
  inline void set_has_chargingflag();
  inline void clear_has_chargingflag();
  inline void set_has_seq();
  inline void clear_has_seq();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 chargingflag_;
  ::google::protobuf::int32 seq_;
  friend void  protobuf_AddDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_AssignDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_dataserver_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static ChargingFlag* default_instance_;
};
// -------------------------------------------------------------------

class GeneralData : public ::google::protobuf::Message {
 public:
  GeneralData();
  virtual ~GeneralData();

  GeneralData(const GeneralData& from);

  inline GeneralData& operator=(const GeneralData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GeneralData& default_instance();

  void Swap(GeneralData* other);

  // implements Message ----------------------------------------------

  inline GeneralData* New() const { return New(NULL); }

  GeneralData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GeneralData& from);
  void MergeFrom(const GeneralData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GeneralData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 GeneralFlag = 1;
  bool has_generalflag() const;
  void clear_generalflag();
  static const int kGeneralFlagFieldNumber = 1;
  ::google::protobuf::int32 generalflag() const;
  void set_generalflag(::google::protobuf::int32 value);

  // optional int32 IO_Number = 2;
  bool has_io_number() const;
  void clear_io_number();
  static const int kIONumberFieldNumber = 2;
  ::google::protobuf::int32 io_number() const;
  void set_io_number(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dataserver_msg.GeneralData)
 private:
  inline void set_has_generalflag();
  inline void clear_has_generalflag();
  inline void set_has_io_number();
  inline void clear_has_io_number();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 generalflag_;
  ::google::protobuf::int32 io_number_;
  friend void  protobuf_AddDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_AssignDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_dataserver_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static GeneralData* default_instance_;
};
// -------------------------------------------------------------------

class Control_CMD_Init_Config : public ::google::protobuf::Message {
 public:
  Control_CMD_Init_Config();
  virtual ~Control_CMD_Init_Config();

  Control_CMD_Init_Config(const Control_CMD_Init_Config& from);

  inline Control_CMD_Init_Config& operator=(const Control_CMD_Init_Config& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Control_CMD_Init_Config& default_instance();

  void Swap(Control_CMD_Init_Config* other);

  // implements Message ----------------------------------------------

  inline Control_CMD_Init_Config* New() const { return New(NULL); }

  Control_CMD_Init_Config* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Control_CMD_Init_Config& from);
  void MergeFrom(const Control_CMD_Init_Config& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Control_CMD_Init_Config* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double stop_delta_distance = 1;
  bool has_stop_delta_distance() const;
  void clear_stop_delta_distance();
  static const int kStopDeltaDistanceFieldNumber = 1;
  double stop_delta_distance() const;
  void set_stop_delta_distance(double value);

  // optional double stop_delta_theta = 2;
  bool has_stop_delta_theta() const;
  void clear_stop_delta_theta();
  static const int kStopDeltaThetaFieldNumber = 2;
  double stop_delta_theta() const;
  void set_stop_delta_theta(double value);

  // optional double nav_v = 3;
  bool has_nav_v() const;
  void clear_nav_v();
  static const int kNavVFieldNumber = 3;
  double nav_v() const;
  void set_nav_v(double value);

  // optional double nav_w = 4;
  bool has_nav_w() const;
  void clear_nav_w();
  static const int kNavWFieldNumber = 4;
  double nav_w() const;
  void set_nav_w(double value);

  // @@protoc_insertion_point(class_scope:dataserver_msg.Control_CMD.Init_Config)
 private:
  inline void set_has_stop_delta_distance();
  inline void clear_has_stop_delta_distance();
  inline void set_has_stop_delta_theta();
  inline void clear_has_stop_delta_theta();
  inline void set_has_nav_v();
  inline void clear_has_nav_v();
  inline void set_has_nav_w();
  inline void clear_has_nav_w();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double stop_delta_distance_;
  double stop_delta_theta_;
  double nav_v_;
  double nav_w_;
  friend void  protobuf_AddDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_AssignDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_dataserver_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static Control_CMD_Init_Config* default_instance_;
};
// -------------------------------------------------------------------

class Control_CMD : public ::google::protobuf::Message {
 public:
  Control_CMD();
  virtual ~Control_CMD();

  Control_CMD(const Control_CMD& from);

  inline Control_CMD& operator=(const Control_CMD& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Control_CMD& default_instance();

  void Swap(Control_CMD* other);

  // implements Message ----------------------------------------------

  inline Control_CMD* New() const { return New(NULL); }

  Control_CMD* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Control_CMD& from);
  void MergeFrom(const Control_CMD& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Control_CMD* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Control_CMD_Init_Config Init_Config;

  // accessors -------------------------------------------------------

  // required int32 CMD_ID = 1;
  bool has_cmd_id() const;
  void clear_cmd_id();
  static const int kCMDIDFieldNumber = 1;
  ::google::protobuf::int32 cmd_id() const;
  void set_cmd_id(::google::protobuf::int32 value);

  // optional .dataserver_msg.Position Goal_pose = 2;
  bool has_goal_pose() const;
  void clear_goal_pose();
  static const int kGoalPoseFieldNumber = 2;
  const ::dataserver_msg::Position& goal_pose() const;
  ::dataserver_msg::Position* mutable_goal_pose();
  ::dataserver_msg::Position* release_goal_pose();
  void set_allocated_goal_pose(::dataserver_msg::Position* goal_pose);

  // optional .dataserver_msg.Velocity velocity = 3;
  bool has_velocity() const;
  void clear_velocity();
  static const int kVelocityFieldNumber = 3;
  const ::dataserver_msg::Velocity& velocity() const;
  ::dataserver_msg::Velocity* mutable_velocity();
  ::dataserver_msg::Velocity* release_velocity();
  void set_allocated_velocity(::dataserver_msg::Velocity* velocity);

  // optional int32 move_mode = 4 [default = 0];
  bool has_move_mode() const;
  void clear_move_mode();
  static const int kMoveModeFieldNumber = 4;
  ::google::protobuf::int32 move_mode() const;
  void set_move_mode(::google::protobuf::int32 value);

  // optional .dataserver_msg.Control_CMD.Init_Config init_cfg = 5;
  bool has_init_cfg() const;
  void clear_init_cfg();
  static const int kInitCfgFieldNumber = 5;
  const ::dataserver_msg::Control_CMD_Init_Config& init_cfg() const;
  ::dataserver_msg::Control_CMD_Init_Config* mutable_init_cfg();
  ::dataserver_msg::Control_CMD_Init_Config* release_init_cfg();
  void set_allocated_init_cfg(::dataserver_msg::Control_CMD_Init_Config* init_cfg);

  // optional int32 projector = 6;
  bool has_projector() const;
  void clear_projector();
  static const int kProjectorFieldNumber = 6;
  ::google::protobuf::int32 projector() const;
  void set_projector(::google::protobuf::int32 value);

  // optional .dataserver_msg.ChargingFlag cf = 7;
  bool has_cf() const;
  void clear_cf();
  static const int kCfFieldNumber = 7;
  const ::dataserver_msg::ChargingFlag& cf() const;
  ::dataserver_msg::ChargingFlag* mutable_cf();
  ::dataserver_msg::ChargingFlag* release_cf();
  void set_allocated_cf(::dataserver_msg::ChargingFlag* cf);

  // optional .dataserver_msg.GeneralData generalData = 8;
  bool has_generaldata() const;
  void clear_generaldata();
  static const int kGeneralDataFieldNumber = 8;
  const ::dataserver_msg::GeneralData& generaldata() const;
  ::dataserver_msg::GeneralData* mutable_generaldata();
  ::dataserver_msg::GeneralData* release_generaldata();
  void set_allocated_generaldata(::dataserver_msg::GeneralData* generaldata);

  // @@protoc_insertion_point(class_scope:dataserver_msg.Control_CMD)
 private:
  inline void set_has_cmd_id();
  inline void clear_has_cmd_id();
  inline void set_has_goal_pose();
  inline void clear_has_goal_pose();
  inline void set_has_velocity();
  inline void clear_has_velocity();
  inline void set_has_move_mode();
  inline void clear_has_move_mode();
  inline void set_has_init_cfg();
  inline void clear_has_init_cfg();
  inline void set_has_projector();
  inline void clear_has_projector();
  inline void set_has_cf();
  inline void clear_has_cf();
  inline void set_has_generaldata();
  inline void clear_has_generaldata();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::dataserver_msg::Position* goal_pose_;
  ::google::protobuf::int32 cmd_id_;
  ::google::protobuf::int32 move_mode_;
  ::dataserver_msg::Velocity* velocity_;
  ::dataserver_msg::Control_CMD_Init_Config* init_cfg_;
  ::dataserver_msg::ChargingFlag* cf_;
  ::dataserver_msg::GeneralData* generaldata_;
  ::google::protobuf::int32 projector_;
  friend void  protobuf_AddDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_AssignDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_dataserver_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static Control_CMD* default_instance_;
};
// -------------------------------------------------------------------

class Response_CMD_Response_flag : public ::google::protobuf::Message {
 public:
  Response_CMD_Response_flag();
  virtual ~Response_CMD_Response_flag();

  Response_CMD_Response_flag(const Response_CMD_Response_flag& from);

  inline Response_CMD_Response_flag& operator=(const Response_CMD_Response_flag& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response_CMD_Response_flag& default_instance();

  void Swap(Response_CMD_Response_flag* other);

  // implements Message ----------------------------------------------

  inline Response_CMD_Response_flag* New() const { return New(NULL); }

  Response_CMD_Response_flag* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response_CMD_Response_flag& from);
  void MergeFrom(const Response_CMD_Response_flag& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Response_CMD_Response_flag* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 Error_ID = 1 [default = -1];
  bool has_error_id() const;
  void clear_error_id();
  static const int kErrorIDFieldNumber = 1;
  ::google::protobuf::int32 error_id() const;
  void set_error_id(::google::protobuf::int32 value);

  // optional int32 cmd_received_flag = 2 [default = -1];
  bool has_cmd_received_flag() const;
  void clear_cmd_received_flag();
  static const int kCmdReceivedFlagFieldNumber = 2;
  ::google::protobuf::int32 cmd_received_flag() const;
  void set_cmd_received_flag(::google::protobuf::int32 value);

  // optional int32 path_formed_flag = 3 [default = -1];
  bool has_path_formed_flag() const;
  void clear_path_formed_flag();
  static const int kPathFormedFlagFieldNumber = 3;
  ::google::protobuf::int32 path_formed_flag() const;
  void set_path_formed_flag(::google::protobuf::int32 value);

  // optional int32 goal_reached_flag = 4 [default = -1];
  bool has_goal_reached_flag() const;
  void clear_goal_reached_flag();
  static const int kGoalReachedFlagFieldNumber = 4;
  ::google::protobuf::int32 goal_reached_flag() const;
  void set_goal_reached_flag(::google::protobuf::int32 value);

  // optional int32 emergency_stop_flag = 5 [default = -1];
  bool has_emergency_stop_flag() const;
  void clear_emergency_stop_flag();
  static const int kEmergencyStopFlagFieldNumber = 5;
  ::google::protobuf::int32 emergency_stop_flag() const;
  void set_emergency_stop_flag(::google::protobuf::int32 value);

  // optional int32 obstacle_forward_flag = 6 [default = -1];
  bool has_obstacle_forward_flag() const;
  void clear_obstacle_forward_flag();
  static const int kObstacleForwardFlagFieldNumber = 6;
  ::google::protobuf::int32 obstacle_forward_flag() const;
  void set_obstacle_forward_flag(::google::protobuf::int32 value);

  // optional int32 move_mode_flag = 7 [default = -1];
  bool has_move_mode_flag() const;
  void clear_move_mode_flag();
  static const int kMoveModeFlagFieldNumber = 7;
  ::google::protobuf::int32 move_mode_flag() const;
  void set_move_mode_flag(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dataserver_msg.Response_CMD.Response_flag)
 private:
  inline void set_has_error_id();
  inline void clear_has_error_id();
  inline void set_has_cmd_received_flag();
  inline void clear_has_cmd_received_flag();
  inline void set_has_path_formed_flag();
  inline void clear_has_path_formed_flag();
  inline void set_has_goal_reached_flag();
  inline void clear_has_goal_reached_flag();
  inline void set_has_emergency_stop_flag();
  inline void clear_has_emergency_stop_flag();
  inline void set_has_obstacle_forward_flag();
  inline void clear_has_obstacle_forward_flag();
  inline void set_has_move_mode_flag();
  inline void clear_has_move_mode_flag();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 error_id_;
  ::google::protobuf::int32 cmd_received_flag_;
  ::google::protobuf::int32 path_formed_flag_;
  ::google::protobuf::int32 goal_reached_flag_;
  ::google::protobuf::int32 emergency_stop_flag_;
  ::google::protobuf::int32 obstacle_forward_flag_;
  ::google::protobuf::int32 move_mode_flag_;
  friend void  protobuf_AddDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_AssignDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_dataserver_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static Response_CMD_Response_flag* default_instance_;
};
// -------------------------------------------------------------------

class Response_CMD : public ::google::protobuf::Message {
 public:
  Response_CMD();
  virtual ~Response_CMD();

  Response_CMD(const Response_CMD& from);

  inline Response_CMD& operator=(const Response_CMD& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response_CMD& default_instance();

  void Swap(Response_CMD* other);

  // implements Message ----------------------------------------------

  inline Response_CMD* New() const { return New(NULL); }

  Response_CMD* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response_CMD& from);
  void MergeFrom(const Response_CMD& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Response_CMD* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Response_CMD_Response_flag Response_flag;

  // accessors -------------------------------------------------------

  // required int32 CMD_ID = 1;
  bool has_cmd_id() const;
  void clear_cmd_id();
  static const int kCMDIDFieldNumber = 1;
  ::google::protobuf::int32 cmd_id() const;
  void set_cmd_id(::google::protobuf::int32 value);

  // optional .dataserver_msg.Response_CMD.Response_flag response_flags = 2;
  bool has_response_flags() const;
  void clear_response_flags();
  static const int kResponseFlagsFieldNumber = 2;
  const ::dataserver_msg::Response_CMD_Response_flag& response_flags() const;
  ::dataserver_msg::Response_CMD_Response_flag* mutable_response_flags();
  ::dataserver_msg::Response_CMD_Response_flag* release_response_flags();
  void set_allocated_response_flags(::dataserver_msg::Response_CMD_Response_flag* response_flags);

  // optional .dataserver_msg.Position robot_pose = 3;
  bool has_robot_pose() const;
  void clear_robot_pose();
  static const int kRobotPoseFieldNumber = 3;
  const ::dataserver_msg::Position& robot_pose() const;
  ::dataserver_msg::Position* mutable_robot_pose();
  ::dataserver_msg::Position* release_robot_pose();
  void set_allocated_robot_pose(::dataserver_msg::Position* robot_pose);

  // optional int32 battery_capacity = 4 [default = -1];
  bool has_battery_capacity() const;
  void clear_battery_capacity();
  static const int kBatteryCapacityFieldNumber = 4;
  ::google::protobuf::int32 battery_capacity() const;
  void set_battery_capacity(::google::protobuf::int32 value);

  // optional int32 charging_flag = 5;
  bool has_charging_flag() const;
  void clear_charging_flag();
  static const int kChargingFlagFieldNumber = 5;
  ::google::protobuf::int32 charging_flag() const;
  void set_charging_flag(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dataserver_msg.Response_CMD)
 private:
  inline void set_has_cmd_id();
  inline void clear_has_cmd_id();
  inline void set_has_response_flags();
  inline void clear_has_response_flags();
  inline void set_has_robot_pose();
  inline void clear_has_robot_pose();
  inline void set_has_battery_capacity();
  inline void clear_has_battery_capacity();
  inline void set_has_charging_flag();
  inline void clear_has_charging_flag();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::dataserver_msg::Response_CMD_Response_flag* response_flags_;
  ::google::protobuf::int32 cmd_id_;
  ::google::protobuf::int32 battery_capacity_;
  ::dataserver_msg::Position* robot_pose_;
  ::google::protobuf::int32 charging_flag_;
  friend void  protobuf_AddDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_AssignDesc_dataserver_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_dataserver_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static Response_CMD* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Position

// required double x = 1;
inline bool Position::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Position::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Position::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Position::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Position::x() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Position.x)
  return x_;
}
inline void Position::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Position.x)
}

// required double y = 2;
inline bool Position::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Position::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Position::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Position::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Position::y() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Position.y)
  return y_;
}
inline void Position::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Position.y)
}

// optional double theta = 3;
inline bool Position::has_theta() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Position::set_has_theta() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Position::clear_has_theta() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Position::clear_theta() {
  theta_ = 0;
  clear_has_theta();
}
inline double Position::theta() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Position.theta)
  return theta_;
}
inline void Position::set_theta(double value) {
  set_has_theta();
  theta_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Position.theta)
}

// optional int32 seq = 4 [default = -1];
inline bool Position::has_seq() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Position::set_has_seq() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Position::clear_has_seq() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Position::clear_seq() {
  seq_ = -1;
  clear_has_seq();
}
inline ::google::protobuf::int32 Position::seq() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Position.seq)
  return seq_;
}
inline void Position::set_seq(::google::protobuf::int32 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Position.seq)
}

// -------------------------------------------------------------------

// Velocity

// required double v = 1 [default = 0];
inline bool Velocity::has_v() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Velocity::set_has_v() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Velocity::clear_has_v() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Velocity::clear_v() {
  v_ = 0;
  clear_has_v();
}
inline double Velocity::v() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Velocity.v)
  return v_;
}
inline void Velocity::set_v(double value) {
  set_has_v();
  v_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Velocity.v)
}

// required double w = 2 [default = 0];
inline bool Velocity::has_w() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Velocity::set_has_w() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Velocity::clear_has_w() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Velocity::clear_w() {
  w_ = 0;
  clear_has_w();
}
inline double Velocity::w() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Velocity.w)
  return w_;
}
inline void Velocity::set_w(double value) {
  set_has_w();
  w_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Velocity.w)
}

// optional double v2 = 3 [default = 0];
inline bool Velocity::has_v2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Velocity::set_has_v2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Velocity::clear_has_v2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Velocity::clear_v2() {
  v2_ = 0;
  clear_has_v2();
}
inline double Velocity::v2() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Velocity.v2)
  return v2_;
}
inline void Velocity::set_v2(double value) {
  set_has_v2();
  v2_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Velocity.v2)
}

// -------------------------------------------------------------------

// ChargingFlag

// optional int32 chargingFlag = 1 [default = 0];
inline bool ChargingFlag::has_chargingflag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChargingFlag::set_has_chargingflag() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChargingFlag::clear_has_chargingflag() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChargingFlag::clear_chargingflag() {
  chargingflag_ = 0;
  clear_has_chargingflag();
}
inline ::google::protobuf::int32 ChargingFlag::chargingflag() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.ChargingFlag.chargingFlag)
  return chargingflag_;
}
inline void ChargingFlag::set_chargingflag(::google::protobuf::int32 value) {
  set_has_chargingflag();
  chargingflag_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.ChargingFlag.chargingFlag)
}

// optional int32 seq = 2 [default = 0];
inline bool ChargingFlag::has_seq() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChargingFlag::set_has_seq() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChargingFlag::clear_has_seq() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChargingFlag::clear_seq() {
  seq_ = 0;
  clear_has_seq();
}
inline ::google::protobuf::int32 ChargingFlag::seq() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.ChargingFlag.seq)
  return seq_;
}
inline void ChargingFlag::set_seq(::google::protobuf::int32 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.ChargingFlag.seq)
}

// -------------------------------------------------------------------

// GeneralData

// optional int32 GeneralFlag = 1;
inline bool GeneralData::has_generalflag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GeneralData::set_has_generalflag() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GeneralData::clear_has_generalflag() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GeneralData::clear_generalflag() {
  generalflag_ = 0;
  clear_has_generalflag();
}
inline ::google::protobuf::int32 GeneralData::generalflag() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.GeneralData.GeneralFlag)
  return generalflag_;
}
inline void GeneralData::set_generalflag(::google::protobuf::int32 value) {
  set_has_generalflag();
  generalflag_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.GeneralData.GeneralFlag)
}

// optional int32 IO_Number = 2;
inline bool GeneralData::has_io_number() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GeneralData::set_has_io_number() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GeneralData::clear_has_io_number() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GeneralData::clear_io_number() {
  io_number_ = 0;
  clear_has_io_number();
}
inline ::google::protobuf::int32 GeneralData::io_number() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.GeneralData.IO_Number)
  return io_number_;
}
inline void GeneralData::set_io_number(::google::protobuf::int32 value) {
  set_has_io_number();
  io_number_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.GeneralData.IO_Number)
}

// -------------------------------------------------------------------

// Control_CMD_Init_Config

// optional double stop_delta_distance = 1;
inline bool Control_CMD_Init_Config::has_stop_delta_distance() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Control_CMD_Init_Config::set_has_stop_delta_distance() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Control_CMD_Init_Config::clear_has_stop_delta_distance() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Control_CMD_Init_Config::clear_stop_delta_distance() {
  stop_delta_distance_ = 0;
  clear_has_stop_delta_distance();
}
inline double Control_CMD_Init_Config::stop_delta_distance() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.Init_Config.stop_delta_distance)
  return stop_delta_distance_;
}
inline void Control_CMD_Init_Config::set_stop_delta_distance(double value) {
  set_has_stop_delta_distance();
  stop_delta_distance_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Control_CMD.Init_Config.stop_delta_distance)
}

// optional double stop_delta_theta = 2;
inline bool Control_CMD_Init_Config::has_stop_delta_theta() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Control_CMD_Init_Config::set_has_stop_delta_theta() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Control_CMD_Init_Config::clear_has_stop_delta_theta() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Control_CMD_Init_Config::clear_stop_delta_theta() {
  stop_delta_theta_ = 0;
  clear_has_stop_delta_theta();
}
inline double Control_CMD_Init_Config::stop_delta_theta() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.Init_Config.stop_delta_theta)
  return stop_delta_theta_;
}
inline void Control_CMD_Init_Config::set_stop_delta_theta(double value) {
  set_has_stop_delta_theta();
  stop_delta_theta_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Control_CMD.Init_Config.stop_delta_theta)
}

// optional double nav_v = 3;
inline bool Control_CMD_Init_Config::has_nav_v() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Control_CMD_Init_Config::set_has_nav_v() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Control_CMD_Init_Config::clear_has_nav_v() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Control_CMD_Init_Config::clear_nav_v() {
  nav_v_ = 0;
  clear_has_nav_v();
}
inline double Control_CMD_Init_Config::nav_v() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.Init_Config.nav_v)
  return nav_v_;
}
inline void Control_CMD_Init_Config::set_nav_v(double value) {
  set_has_nav_v();
  nav_v_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Control_CMD.Init_Config.nav_v)
}

// optional double nav_w = 4;
inline bool Control_CMD_Init_Config::has_nav_w() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Control_CMD_Init_Config::set_has_nav_w() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Control_CMD_Init_Config::clear_has_nav_w() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Control_CMD_Init_Config::clear_nav_w() {
  nav_w_ = 0;
  clear_has_nav_w();
}
inline double Control_CMD_Init_Config::nav_w() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.Init_Config.nav_w)
  return nav_w_;
}
inline void Control_CMD_Init_Config::set_nav_w(double value) {
  set_has_nav_w();
  nav_w_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Control_CMD.Init_Config.nav_w)
}

// -------------------------------------------------------------------

// Control_CMD

// required int32 CMD_ID = 1;
inline bool Control_CMD::has_cmd_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Control_CMD::set_has_cmd_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Control_CMD::clear_has_cmd_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Control_CMD::clear_cmd_id() {
  cmd_id_ = 0;
  clear_has_cmd_id();
}
inline ::google::protobuf::int32 Control_CMD::cmd_id() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.CMD_ID)
  return cmd_id_;
}
inline void Control_CMD::set_cmd_id(::google::protobuf::int32 value) {
  set_has_cmd_id();
  cmd_id_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Control_CMD.CMD_ID)
}

// optional .dataserver_msg.Position Goal_pose = 2;
inline bool Control_CMD::has_goal_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Control_CMD::set_has_goal_pose() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Control_CMD::clear_has_goal_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Control_CMD::clear_goal_pose() {
  if (goal_pose_ != NULL) goal_pose_->::dataserver_msg::Position::Clear();
  clear_has_goal_pose();
}
inline const ::dataserver_msg::Position& Control_CMD::goal_pose() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.Goal_pose)
  return goal_pose_ != NULL ? *goal_pose_ : *default_instance_->goal_pose_;
}
inline ::dataserver_msg::Position* Control_CMD::mutable_goal_pose() {
  set_has_goal_pose();
  if (goal_pose_ == NULL) {
    goal_pose_ = new ::dataserver_msg::Position;
  }
  // @@protoc_insertion_point(field_mutable:dataserver_msg.Control_CMD.Goal_pose)
  return goal_pose_;
}
inline ::dataserver_msg::Position* Control_CMD::release_goal_pose() {
  clear_has_goal_pose();
  ::dataserver_msg::Position* temp = goal_pose_;
  goal_pose_ = NULL;
  return temp;
}
inline void Control_CMD::set_allocated_goal_pose(::dataserver_msg::Position* goal_pose) {
  delete goal_pose_;
  goal_pose_ = goal_pose;
  if (goal_pose) {
    set_has_goal_pose();
  } else {
    clear_has_goal_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:dataserver_msg.Control_CMD.Goal_pose)
}

// optional .dataserver_msg.Velocity velocity = 3;
inline bool Control_CMD::has_velocity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Control_CMD::set_has_velocity() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Control_CMD::clear_has_velocity() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Control_CMD::clear_velocity() {
  if (velocity_ != NULL) velocity_->::dataserver_msg::Velocity::Clear();
  clear_has_velocity();
}
inline const ::dataserver_msg::Velocity& Control_CMD::velocity() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.velocity)
  return velocity_ != NULL ? *velocity_ : *default_instance_->velocity_;
}
inline ::dataserver_msg::Velocity* Control_CMD::mutable_velocity() {
  set_has_velocity();
  if (velocity_ == NULL) {
    velocity_ = new ::dataserver_msg::Velocity;
  }
  // @@protoc_insertion_point(field_mutable:dataserver_msg.Control_CMD.velocity)
  return velocity_;
}
inline ::dataserver_msg::Velocity* Control_CMD::release_velocity() {
  clear_has_velocity();
  ::dataserver_msg::Velocity* temp = velocity_;
  velocity_ = NULL;
  return temp;
}
inline void Control_CMD::set_allocated_velocity(::dataserver_msg::Velocity* velocity) {
  delete velocity_;
  velocity_ = velocity;
  if (velocity) {
    set_has_velocity();
  } else {
    clear_has_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:dataserver_msg.Control_CMD.velocity)
}

// optional int32 move_mode = 4 [default = 0];
inline bool Control_CMD::has_move_mode() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Control_CMD::set_has_move_mode() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Control_CMD::clear_has_move_mode() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Control_CMD::clear_move_mode() {
  move_mode_ = 0;
  clear_has_move_mode();
}
inline ::google::protobuf::int32 Control_CMD::move_mode() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.move_mode)
  return move_mode_;
}
inline void Control_CMD::set_move_mode(::google::protobuf::int32 value) {
  set_has_move_mode();
  move_mode_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Control_CMD.move_mode)
}

// optional .dataserver_msg.Control_CMD.Init_Config init_cfg = 5;
inline bool Control_CMD::has_init_cfg() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Control_CMD::set_has_init_cfg() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Control_CMD::clear_has_init_cfg() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Control_CMD::clear_init_cfg() {
  if (init_cfg_ != NULL) init_cfg_->::dataserver_msg::Control_CMD_Init_Config::Clear();
  clear_has_init_cfg();
}
inline const ::dataserver_msg::Control_CMD_Init_Config& Control_CMD::init_cfg() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.init_cfg)
  return init_cfg_ != NULL ? *init_cfg_ : *default_instance_->init_cfg_;
}
inline ::dataserver_msg::Control_CMD_Init_Config* Control_CMD::mutable_init_cfg() {
  set_has_init_cfg();
  if (init_cfg_ == NULL) {
    init_cfg_ = new ::dataserver_msg::Control_CMD_Init_Config;
  }
  // @@protoc_insertion_point(field_mutable:dataserver_msg.Control_CMD.init_cfg)
  return init_cfg_;
}
inline ::dataserver_msg::Control_CMD_Init_Config* Control_CMD::release_init_cfg() {
  clear_has_init_cfg();
  ::dataserver_msg::Control_CMD_Init_Config* temp = init_cfg_;
  init_cfg_ = NULL;
  return temp;
}
inline void Control_CMD::set_allocated_init_cfg(::dataserver_msg::Control_CMD_Init_Config* init_cfg) {
  delete init_cfg_;
  init_cfg_ = init_cfg;
  if (init_cfg) {
    set_has_init_cfg();
  } else {
    clear_has_init_cfg();
  }
  // @@protoc_insertion_point(field_set_allocated:dataserver_msg.Control_CMD.init_cfg)
}

// optional int32 projector = 6;
inline bool Control_CMD::has_projector() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Control_CMD::set_has_projector() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Control_CMD::clear_has_projector() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Control_CMD::clear_projector() {
  projector_ = 0;
  clear_has_projector();
}
inline ::google::protobuf::int32 Control_CMD::projector() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.projector)
  return projector_;
}
inline void Control_CMD::set_projector(::google::protobuf::int32 value) {
  set_has_projector();
  projector_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Control_CMD.projector)
}

// optional .dataserver_msg.ChargingFlag cf = 7;
inline bool Control_CMD::has_cf() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Control_CMD::set_has_cf() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Control_CMD::clear_has_cf() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Control_CMD::clear_cf() {
  if (cf_ != NULL) cf_->::dataserver_msg::ChargingFlag::Clear();
  clear_has_cf();
}
inline const ::dataserver_msg::ChargingFlag& Control_CMD::cf() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.cf)
  return cf_ != NULL ? *cf_ : *default_instance_->cf_;
}
inline ::dataserver_msg::ChargingFlag* Control_CMD::mutable_cf() {
  set_has_cf();
  if (cf_ == NULL) {
    cf_ = new ::dataserver_msg::ChargingFlag;
  }
  // @@protoc_insertion_point(field_mutable:dataserver_msg.Control_CMD.cf)
  return cf_;
}
inline ::dataserver_msg::ChargingFlag* Control_CMD::release_cf() {
  clear_has_cf();
  ::dataserver_msg::ChargingFlag* temp = cf_;
  cf_ = NULL;
  return temp;
}
inline void Control_CMD::set_allocated_cf(::dataserver_msg::ChargingFlag* cf) {
  delete cf_;
  cf_ = cf;
  if (cf) {
    set_has_cf();
  } else {
    clear_has_cf();
  }
  // @@protoc_insertion_point(field_set_allocated:dataserver_msg.Control_CMD.cf)
}

// optional .dataserver_msg.GeneralData generalData = 8;
inline bool Control_CMD::has_generaldata() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Control_CMD::set_has_generaldata() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Control_CMD::clear_has_generaldata() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Control_CMD::clear_generaldata() {
  if (generaldata_ != NULL) generaldata_->::dataserver_msg::GeneralData::Clear();
  clear_has_generaldata();
}
inline const ::dataserver_msg::GeneralData& Control_CMD::generaldata() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Control_CMD.generalData)
  return generaldata_ != NULL ? *generaldata_ : *default_instance_->generaldata_;
}
inline ::dataserver_msg::GeneralData* Control_CMD::mutable_generaldata() {
  set_has_generaldata();
  if (generaldata_ == NULL) {
    generaldata_ = new ::dataserver_msg::GeneralData;
  }
  // @@protoc_insertion_point(field_mutable:dataserver_msg.Control_CMD.generalData)
  return generaldata_;
}
inline ::dataserver_msg::GeneralData* Control_CMD::release_generaldata() {
  clear_has_generaldata();
  ::dataserver_msg::GeneralData* temp = generaldata_;
  generaldata_ = NULL;
  return temp;
}
inline void Control_CMD::set_allocated_generaldata(::dataserver_msg::GeneralData* generaldata) {
  delete generaldata_;
  generaldata_ = generaldata;
  if (generaldata) {
    set_has_generaldata();
  } else {
    clear_has_generaldata();
  }
  // @@protoc_insertion_point(field_set_allocated:dataserver_msg.Control_CMD.generalData)
}

// -------------------------------------------------------------------

// Response_CMD_Response_flag

// optional int32 Error_ID = 1 [default = -1];
inline bool Response_CMD_Response_flag::has_error_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response_CMD_Response_flag::set_has_error_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response_CMD_Response_flag::clear_has_error_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response_CMD_Response_flag::clear_error_id() {
  error_id_ = -1;
  clear_has_error_id();
}
inline ::google::protobuf::int32 Response_CMD_Response_flag::error_id() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.Response_flag.Error_ID)
  return error_id_;
}
inline void Response_CMD_Response_flag::set_error_id(::google::protobuf::int32 value) {
  set_has_error_id();
  error_id_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Response_CMD.Response_flag.Error_ID)
}

// optional int32 cmd_received_flag = 2 [default = -1];
inline bool Response_CMD_Response_flag::has_cmd_received_flag() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response_CMD_Response_flag::set_has_cmd_received_flag() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response_CMD_Response_flag::clear_has_cmd_received_flag() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response_CMD_Response_flag::clear_cmd_received_flag() {
  cmd_received_flag_ = -1;
  clear_has_cmd_received_flag();
}
inline ::google::protobuf::int32 Response_CMD_Response_flag::cmd_received_flag() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.Response_flag.cmd_received_flag)
  return cmd_received_flag_;
}
inline void Response_CMD_Response_flag::set_cmd_received_flag(::google::protobuf::int32 value) {
  set_has_cmd_received_flag();
  cmd_received_flag_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Response_CMD.Response_flag.cmd_received_flag)
}

// optional int32 path_formed_flag = 3 [default = -1];
inline bool Response_CMD_Response_flag::has_path_formed_flag() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Response_CMD_Response_flag::set_has_path_formed_flag() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Response_CMD_Response_flag::clear_has_path_formed_flag() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Response_CMD_Response_flag::clear_path_formed_flag() {
  path_formed_flag_ = -1;
  clear_has_path_formed_flag();
}
inline ::google::protobuf::int32 Response_CMD_Response_flag::path_formed_flag() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.Response_flag.path_formed_flag)
  return path_formed_flag_;
}
inline void Response_CMD_Response_flag::set_path_formed_flag(::google::protobuf::int32 value) {
  set_has_path_formed_flag();
  path_formed_flag_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Response_CMD.Response_flag.path_formed_flag)
}

// optional int32 goal_reached_flag = 4 [default = -1];
inline bool Response_CMD_Response_flag::has_goal_reached_flag() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Response_CMD_Response_flag::set_has_goal_reached_flag() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Response_CMD_Response_flag::clear_has_goal_reached_flag() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Response_CMD_Response_flag::clear_goal_reached_flag() {
  goal_reached_flag_ = -1;
  clear_has_goal_reached_flag();
}
inline ::google::protobuf::int32 Response_CMD_Response_flag::goal_reached_flag() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.Response_flag.goal_reached_flag)
  return goal_reached_flag_;
}
inline void Response_CMD_Response_flag::set_goal_reached_flag(::google::protobuf::int32 value) {
  set_has_goal_reached_flag();
  goal_reached_flag_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Response_CMD.Response_flag.goal_reached_flag)
}

// optional int32 emergency_stop_flag = 5 [default = -1];
inline bool Response_CMD_Response_flag::has_emergency_stop_flag() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Response_CMD_Response_flag::set_has_emergency_stop_flag() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Response_CMD_Response_flag::clear_has_emergency_stop_flag() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Response_CMD_Response_flag::clear_emergency_stop_flag() {
  emergency_stop_flag_ = -1;
  clear_has_emergency_stop_flag();
}
inline ::google::protobuf::int32 Response_CMD_Response_flag::emergency_stop_flag() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.Response_flag.emergency_stop_flag)
  return emergency_stop_flag_;
}
inline void Response_CMD_Response_flag::set_emergency_stop_flag(::google::protobuf::int32 value) {
  set_has_emergency_stop_flag();
  emergency_stop_flag_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Response_CMD.Response_flag.emergency_stop_flag)
}

// optional int32 obstacle_forward_flag = 6 [default = -1];
inline bool Response_CMD_Response_flag::has_obstacle_forward_flag() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Response_CMD_Response_flag::set_has_obstacle_forward_flag() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Response_CMD_Response_flag::clear_has_obstacle_forward_flag() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Response_CMD_Response_flag::clear_obstacle_forward_flag() {
  obstacle_forward_flag_ = -1;
  clear_has_obstacle_forward_flag();
}
inline ::google::protobuf::int32 Response_CMD_Response_flag::obstacle_forward_flag() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.Response_flag.obstacle_forward_flag)
  return obstacle_forward_flag_;
}
inline void Response_CMD_Response_flag::set_obstacle_forward_flag(::google::protobuf::int32 value) {
  set_has_obstacle_forward_flag();
  obstacle_forward_flag_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Response_CMD.Response_flag.obstacle_forward_flag)
}

// optional int32 move_mode_flag = 7 [default = -1];
inline bool Response_CMD_Response_flag::has_move_mode_flag() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Response_CMD_Response_flag::set_has_move_mode_flag() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Response_CMD_Response_flag::clear_has_move_mode_flag() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Response_CMD_Response_flag::clear_move_mode_flag() {
  move_mode_flag_ = -1;
  clear_has_move_mode_flag();
}
inline ::google::protobuf::int32 Response_CMD_Response_flag::move_mode_flag() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.Response_flag.move_mode_flag)
  return move_mode_flag_;
}
inline void Response_CMD_Response_flag::set_move_mode_flag(::google::protobuf::int32 value) {
  set_has_move_mode_flag();
  move_mode_flag_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Response_CMD.Response_flag.move_mode_flag)
}

// -------------------------------------------------------------------

// Response_CMD

// required int32 CMD_ID = 1;
inline bool Response_CMD::has_cmd_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response_CMD::set_has_cmd_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response_CMD::clear_has_cmd_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response_CMD::clear_cmd_id() {
  cmd_id_ = 0;
  clear_has_cmd_id();
}
inline ::google::protobuf::int32 Response_CMD::cmd_id() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.CMD_ID)
  return cmd_id_;
}
inline void Response_CMD::set_cmd_id(::google::protobuf::int32 value) {
  set_has_cmd_id();
  cmd_id_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Response_CMD.CMD_ID)
}

// optional .dataserver_msg.Response_CMD.Response_flag response_flags = 2;
inline bool Response_CMD::has_response_flags() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response_CMD::set_has_response_flags() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response_CMD::clear_has_response_flags() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response_CMD::clear_response_flags() {
  if (response_flags_ != NULL) response_flags_->::dataserver_msg::Response_CMD_Response_flag::Clear();
  clear_has_response_flags();
}
inline const ::dataserver_msg::Response_CMD_Response_flag& Response_CMD::response_flags() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.response_flags)
  return response_flags_ != NULL ? *response_flags_ : *default_instance_->response_flags_;
}
inline ::dataserver_msg::Response_CMD_Response_flag* Response_CMD::mutable_response_flags() {
  set_has_response_flags();
  if (response_flags_ == NULL) {
    response_flags_ = new ::dataserver_msg::Response_CMD_Response_flag;
  }
  // @@protoc_insertion_point(field_mutable:dataserver_msg.Response_CMD.response_flags)
  return response_flags_;
}
inline ::dataserver_msg::Response_CMD_Response_flag* Response_CMD::release_response_flags() {
  clear_has_response_flags();
  ::dataserver_msg::Response_CMD_Response_flag* temp = response_flags_;
  response_flags_ = NULL;
  return temp;
}
inline void Response_CMD::set_allocated_response_flags(::dataserver_msg::Response_CMD_Response_flag* response_flags) {
  delete response_flags_;
  response_flags_ = response_flags;
  if (response_flags) {
    set_has_response_flags();
  } else {
    clear_has_response_flags();
  }
  // @@protoc_insertion_point(field_set_allocated:dataserver_msg.Response_CMD.response_flags)
}

// optional .dataserver_msg.Position robot_pose = 3;
inline bool Response_CMD::has_robot_pose() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Response_CMD::set_has_robot_pose() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Response_CMD::clear_has_robot_pose() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Response_CMD::clear_robot_pose() {
  if (robot_pose_ != NULL) robot_pose_->::dataserver_msg::Position::Clear();
  clear_has_robot_pose();
}
inline const ::dataserver_msg::Position& Response_CMD::robot_pose() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.robot_pose)
  return robot_pose_ != NULL ? *robot_pose_ : *default_instance_->robot_pose_;
}
inline ::dataserver_msg::Position* Response_CMD::mutable_robot_pose() {
  set_has_robot_pose();
  if (robot_pose_ == NULL) {
    robot_pose_ = new ::dataserver_msg::Position;
  }
  // @@protoc_insertion_point(field_mutable:dataserver_msg.Response_CMD.robot_pose)
  return robot_pose_;
}
inline ::dataserver_msg::Position* Response_CMD::release_robot_pose() {
  clear_has_robot_pose();
  ::dataserver_msg::Position* temp = robot_pose_;
  robot_pose_ = NULL;
  return temp;
}
inline void Response_CMD::set_allocated_robot_pose(::dataserver_msg::Position* robot_pose) {
  delete robot_pose_;
  robot_pose_ = robot_pose;
  if (robot_pose) {
    set_has_robot_pose();
  } else {
    clear_has_robot_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:dataserver_msg.Response_CMD.robot_pose)
}

// optional int32 battery_capacity = 4 [default = -1];
inline bool Response_CMD::has_battery_capacity() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Response_CMD::set_has_battery_capacity() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Response_CMD::clear_has_battery_capacity() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Response_CMD::clear_battery_capacity() {
  battery_capacity_ = -1;
  clear_has_battery_capacity();
}
inline ::google::protobuf::int32 Response_CMD::battery_capacity() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.battery_capacity)
  return battery_capacity_;
}
inline void Response_CMD::set_battery_capacity(::google::protobuf::int32 value) {
  set_has_battery_capacity();
  battery_capacity_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Response_CMD.battery_capacity)
}

// optional int32 charging_flag = 5;
inline bool Response_CMD::has_charging_flag() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Response_CMD::set_has_charging_flag() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Response_CMD::clear_has_charging_flag() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Response_CMD::clear_charging_flag() {
  charging_flag_ = 0;
  clear_has_charging_flag();
}
inline ::google::protobuf::int32 Response_CMD::charging_flag() const {
  // @@protoc_insertion_point(field_get:dataserver_msg.Response_CMD.charging_flag)
  return charging_flag_;
}
inline void Response_CMD::set_charging_flag(::google::protobuf::int32 value) {
  set_has_charging_flag();
  charging_flag_ = value;
  // @@protoc_insertion_point(field_set:dataserver_msg.Response_CMD.charging_flag)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dataserver_msg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dataserver_5fmsg_2eproto__INCLUDED
